[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xffffff"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "0xeeeeee"
text = "0x111111"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x111111"
foreground = "0xeeeeee"

[colors.selection]
background = "0x555555"
text = "0x111111"

[cursor]
style = "Beam"

[font]
size = 17.0

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[keyboard]
